In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
dataset = pd.read_csv('train_HP.csv')
dataset.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [2]:
def getNanColNames(df):
    colnames = df.columns
    cols_con_na = []
    for col in colnames:
        if(df[col].isnull().sum() > 0):
            cols_con_na.append(col)
    return cols_con_na
cols_con_nan = getNanColNames(dataset)
cols_con_nan

['LotFrontage',
 'Alley',
 'MasVnrType',
 'MasVnrArea',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature']

In [7]:
dataset[cols_con_nan].isnull().mean()

LotFrontage     0.177397
Alley           0.937671
MasVnrType      0.005479
MasVnrArea      0.005479
BsmtQual        0.025342
BsmtCond        0.025342
BsmtExposure    0.026027
BsmtFinType1    0.025342
BsmtFinType2    0.026027
Electrical      0.000685
FireplaceQu     0.472603
GarageType      0.055479
GarageYrBlt     0.055479
GarageFinish    0.055479
GarageQual      0.055479
GarageCond      0.055479
PoolQC          0.995205
Fence           0.807534
MiscFeature     0.963014
dtype: float64

In [8]:
dataset[cols_con_nan].dtypes

LotFrontage     float64
Alley            object
MasVnrType       object
MasVnrArea      float64
BsmtQual         object
BsmtCond         object
BsmtExposure     object
BsmtFinType1     object
BsmtFinType2     object
Electrical       object
FireplaceQu      object
GarageType       object
GarageYrBlt     float64
GarageFinish     object
GarageQual       object
GarageCond       object
PoolQC           object
Fence            object
MiscFeature      object
dtype: object

In [9]:
dataset['LotFrontage'].fillna(int(dataset['LotFrontage'].mean()), inplace=True)
dataset['MasVnrArea'].fillna(int(dataset['MasVnrArea'].mean()), inplace=True)
dataset['GarageYrBlt'].fillna(int(dataset['GarageYrBlt'].mean()), inplace=True)

In [10]:
def getNanColNames(df):
    colnames = df.columns
    cols_con_na = []
    for col in colnames:
        if(df[col].isnull().sum() > 0):
            cols_con_na.append(col)
    return cols_con_na
cols_con_nan = getNanColNames(dataset)
cols_con_nan

['Alley',
 'MasVnrType',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature']

In [11]:
dataset['Alley'].fillna('Alley', inplace=True)
dataset['MasVnrType'].fillna('MasVnrType', inplace=True)
dataset['BsmtQual'].fillna('BsmtQual', inplace=True)
dataset['BsmtCond'].fillna('BsmtCond', inplace=True)
dataset['BsmtExposure'].fillna('BsmtExposure', inplace=True)
dataset['BsmtFinType1'].fillna('BsmtFinType1', inplace=True)
dataset['BsmtFinType2'].fillna('BsmtFinType2', inplace=True)
dataset['Electrical'].fillna('Electrical', inplace=True)
dataset['FireplaceQu'].fillna('FireplaceQu', inplace=True)
dataset['GarageType'].fillna('GarageType', inplace=True)
dataset['GarageFinish'].fillna('GarageFinish', inplace=True)
dataset['GarageQual'].fillna('GarageQual', inplace=True)
dataset['GarageCond'].fillna('GarageCond', inplace=True)
dataset['PoolQC'].fillna('PoolQC', inplace=True)
dataset['Fence'].fillna('Fence', inplace=True)
dataset['MiscFeature'].fillna('MiscFeature', inplace=True)

In [13]:
def getCategoryVars(df):
    colnames = df.columns
    cat_cols = []
    for col in colnames:
        if(df[col].dtype == 'object'):
            cat_cols.append(col)
    return cat_cols
cat_cols = getCategoryVars(dataset)
cat_cols

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']

In [14]:
def executeFreqEncoding(df, map_type='freq'):
    colnames = df.columns
    for col in colnames:
        if(df[col].dtype == 'object'):
            factor_div = 1 if (map_type == 'freq') else len(df[col])
            mapper = (df[col].value_counts().sort_values(ascending=False)/factor_div).to_dict()
            df[col] = df[col].map(mapper)

In [15]:
executeFreqEncoding(dataset)
dataset

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,1151.0,65.0,8450,1454.0,1369.0,925.0,1311.0,1459.0,...,0,1453.0,1179.0,1406.0,0,2,2008,1267.0,1198.0,208500
1,2,20,1151.0,80.0,9600,1454.0,1369.0,925.0,1311.0,1459.0,...,0,1453.0,1179.0,1406.0,0,5,2007,1267.0,1198.0,181500
2,3,60,1151.0,68.0,11250,1454.0,1369.0,484.0,1311.0,1459.0,...,0,1453.0,1179.0,1406.0,0,9,2008,1267.0,1198.0,223500
3,4,70,1151.0,60.0,9550,1454.0,1369.0,484.0,1311.0,1459.0,...,0,1453.0,1179.0,1406.0,0,2,2006,1267.0,101.0,140000
4,5,60,1151.0,84.0,14260,1454.0,1369.0,484.0,1311.0,1459.0,...,0,1453.0,1179.0,1406.0,0,12,2008,1267.0,1198.0,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,1151.0,62.0,7917,1454.0,1369.0,925.0,1311.0,1459.0,...,0,1453.0,1179.0,1406.0,0,8,2007,1267.0,1198.0,175000
1456,1457,20,1151.0,85.0,13175,1454.0,1369.0,925.0,1311.0,1459.0,...,0,1453.0,157.0,1406.0,0,2,2010,1267.0,1198.0,210000
1457,1458,70,1151.0,66.0,9042,1454.0,1369.0,925.0,1311.0,1459.0,...,0,1453.0,59.0,49.0,2500,5,2010,1267.0,1198.0,266500
1458,1459,20,1151.0,68.0,9717,1454.0,1369.0,925.0,1311.0,1459.0,...,0,1453.0,1179.0,1406.0,0,4,2010,1267.0,1198.0,142125
1459,1460,20,1151.0,75.0,9937,1454.0,1369.0,925.0,1311.0,1459.0,...,0,1453.0,1179.0,1406.0,0,6,2008,1267.0,1198.0,147500

In [16]:
import scipy.stats as stats

In [17]:
def getContinuesCols(df):
    colnames = df.columns
    numeric_continues_vars = []
    for col in colnames:
        unique_values =len (df[col].unique())
        if((df[col].dtype != 'object') and (unique_values > 30)):
            numeric_continues_vars.append(col)
    return numeric_continues_vars
numeric_cont_vars = getContinuesCols(dataset)
numeric_cont_vars

['Id',
 'LotFrontage',
 'LotArea',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'GrLivArea',
 'GarageYrBlt',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 'ScreenPorch',
 'SalePrice']

In [18]:
np.log(dataset['Id'])
np.log(dataset['LotFrontage'])
np.log(dataset['LotArea'])
np.log(dataset['YearBuilt'])
np.log(dataset['YearRemodAdd'])
np.log(dataset['MasVnrArea'])
np.log(dataset['BsmtFinSF1'])
np.log(dataset['BsmtFinSF2'])
np.log(dataset['BsmtUnfSF'])
np.log(dataset['TotalBsmtSF'])
np.log(dataset['1stFlrSF'])
np.log(dataset['2ndFlrSF'])
np.log(dataset['GrLivArea'])
np.log(dataset['GarageYrBlt'])
np.log(dataset['GarageArea'])
np.log(dataset['WoodDeckSF'])
np.log(dataset['OpenPorchSF'])
np.log(dataset['EnclosedPorch'])
np.log(dataset['ScreenPorch'])
np.log(dataset['SalePrice'])

C:\Users\jamm_\anaconda3\lib\site-packages\pandas\core\arraylike.py:364: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

0       12.247694
1       12.109011
2       12.317167
3       11.849398
4       12.429216
          ...
1455    12.072541
1456    12.254863
1457    12.493130
1458    11.864462
1459    11.901583
Name: SalePrice, Length: 1460, dtype: float64

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
dataset.describe()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
count,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,943.086301,70.041096,10516.828082,1448.049315,1286.535616,747.713699,1182.524658,1458.001370,...,2.758904,1446.045205,973.430137,1355.647945,43.489041,6.321918,2007.815753,1111.083562,1001.089041,180921.195890
std,421.610009,42.300571,402.991484,22.024031,9981.264932,92.666405,319.962351,246.500272,381.236281,38.157604,...,40.177307,100.234424,421.854735,257.030425,496.123024,2.703626,1.328095,399.981015,421.481019,79442.502883
min,1.000000,20.000000,10.000000,21.000000,1300.000000,6.000000,41.000000,10.000000,36.000000,1.000000,...,0.000000,2.000000,11.000000,1.000000,0.000000,1.000000,2006.000000,2.000000,4.000000,34900.000000
25%,365.750000,20.000000,1151.000000,60.000000,7553.500000,1454.000000,1369.000000,484.000000,1311.000000,1459.000000,...,0.000000,1453.000000,1179.000000,1406.000000,0.000000,5.000000,2007.000000,1267.000000,1198.000000,129975.000000
50%,730.500000,50.000000,1151.000000,70.000000,9478.500000,1454.000000,1369.000000,925.000000,1311.000000,1459.000000,...,0.000000,1453.000000,1179.000000,1406.000000,0.000000,6.000000,2008.000000,1267.000000,1198.000000,163000.000000
75%,1095.250000,70.000000,1151.000000,79.000000,11601.500000,1454.000000,1369.000000,925.000000,1311.000000,1459.000000,...,0.000000,1453.000000,1179.000000,1406.000000,0.000000,8.000000,2009.000000,1267.000000,1198.000000,214000.000000
max,1460.000000,190.000000,1151.000000,313.000000,215245.000000,1454.000000,1369.000000,925.000000,1311.000000,1459.000000,...,738.000000,1453.000000,1179.000000,1406.000000,15500.000000,12.000000,2010.000000,1267.000000,1198.000000,755000.000000

In [21]:
scaler = StandardScaler()
scaler.fit(dataset)

StandardScaler()

In [22]:
dataset_final = pd.DataFrame(scaler.transform(dataset), columns=dataset.columns)

In [23]:
np.round(dataset_final.describe(), 2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
count,1460.00,1460.00,1460.00,1460.00,1460.00,1460.00,1460.00,1460.00,1460.00,1460.00,...,1460.00,1460.00,1460.00,1460.00,1460.00,1460.00,1460.00,1460.00,1460.00,1460.00
mean,0.00,-0.00,0.00,0.00,-0.00,0.00,0.00,0.00,-0.00,0.00,...,-0.00,0.00,0.00,0.00,0.00,-0.00,0.00,0.00,0.00,0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-1.73,-0.87,-2.32,-2.23,-0.92,-15.57,-3.89,-2.99,-3.01,-38.20,...,-0.07,-14.41,-2.28,-5.27,-0.09,-1.97,-1.37,-2.77,-2.37,-1.84
25%,-0.87,-0.87,0.52,-0.46,-0.30,0.06,0.26,-1.07,0.34,0.03,...,-0.07,0.07,0.49,0.20,-0.09,-0.49,-0.61,0.39,0.47,-0.64
50%,0.00,-0.16,0.52,-0.00,-0.10,0.06,0.26,0.72,0.34,0.03,...,-0.07,0.07,0.49,0.20,-0.09,-0.12,0.14,0.39,0.47,-0.23
75%,0.87,0.31,0.52,0.41,0.11,0.06,0.26,0.72,0.34,0.03,...,-0.07,0.07,0.49,0.20,-0.09,0.62,0.89,0.39,0.47,0.42
max,1.73,3.15,0.52,11.04,20.52,0.06,0.26,0.72,0.34,0.03,...,18.31,0.07,0.49,0.20,31.17,2.10,1.65,0.39,0.47,7.23

In [24]:
corr_matrix = dataset_final.corr(method='pearson')
corr_matrix

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,1.000000,0.011156,0.029658,-0.009616,-0.033226,0.008916,-0.000673,0.030936,-0.015528,-0.013324,...,0.057044,-0.055499,0.005384,0.037958,-0.006242,0.021172,0.000712,0.026305,0.016019,-0.021917
MSSubClass,0.011156,1.000000,-0.341206,-0.357042,-0.139781,-0.024969,-0.149968,0.115940,0.011171,0.022844,...,0.008283,-0.008605,0.103759,0.041357,-0.007683,-0.013585,-0.021407,0.024031,0.022733,-0.084284
MSZoning,0.029658,-0.341206,1.000000,0.316908,0.201708,0.052289,0.364656,-0.238403,-0.000829,-0.013512,...,0.035452,-0.035822,-0.039128,-0.021714,0.017522,-0.007161,0.011659,0.029513,0.059225,0.232941
LotFrontage,-0.009616,-0.357042,0.316908,1.000000,0.306689,-0.037324,0.167799,-0.180418,-0.087164,0.000049,...,0.180867,-0.207475,-0.031407,-0.007358,0.001101,0.010172,0.006750,-0.086160,-0.069680,0.334897
LotArea,-0.033226,-0.139781,0.201708,0.306689,1.000000,-0.197131,0.075753,-0.293928,-0.259117,-0.010123,...,0.077672,-0.087149,0.045617,-0.108488,0.038068,0.001205,-0.014261,-0.001087,0.006296,0.263843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MoSold,0.021172,-0.013585,-0.007161,0.010172,0.001205,0.003690,0.018175,-0.028244,-0.033994,0.051552,...,-0.033737,0.037621,-0.004826,-0.014367,-0.006495,1.000000,-0.145721,-0.085607,-0.069878,0.046432
YrSold,0.000712,-0.021407,0.011659,0.006750,-0.014261,-0.025043,0.017523,0.035395,0.024855,-0.023353,...,-0.059689,0.057594,-0.037608,-0.057068,0.004906,-0.145721,1.000000,0.075423,0.130481,-0.028923
SaleType,0.026305,0.024031,0.029513,-0.086160,-0.001087,0.008635,0.000304,0.018376,-0.011995,0.069934,...,0.003345,0.001318,-0.088367,-0.020035,0.024468,-0.085607,0.075423,1.000000,0.609095,-0.231732
SaleCondition,0.016019,0.022733,0.059225,-0.069680,0.006296,0.000115,0.027734,-0.005489,0.038493,0.055928,...,-0.071545,0.072351,-0.043781,-0.053148,0.037103,-0.069878,0.130481,0.609095,1.000000,-0.146294
SalePrice,-0.021917,-0.084284,0.232941,0.334897,0.263843,0.041036,0.123360,-0.274094,-0.028550,0.014314,...,0.092404,-0.093730,0.170887,0.072257,-0.021190,0.046432,-0.028923,-0.231732,-0.146294,1.000000

In [25]:
def tidy_corr_matrix(corr_mat):
    corr_mat = corr_mat.stack().reset_index()
    corr_mat.columns = ['variable_1','variable_2','r']
    corr_mat = corr_mat.loc[corr_mat['variable_1'] != corr_mat['variable_2'], :]
    corr_mat['abs_r'] = np.abs(corr_mat['r'])
    corr_mat = corr_mat.sort_values('abs_r', ascending=False)
    
    return(corr_mat)

tidy_corr_matrix(corr_matrix).head(10)

        variable_1    variable_2         r     abs_r
5903        PoolQC      PoolArea -0.989654  0.989654
5823      PoolArea        PoolQC -0.989654  0.989654
1887   Exterior1st   Exterior2nd  0.947892  0.947892
1967   Exterior2nd   Exterior1st  0.947892  0.947892
5083    GarageArea    GarageCars  0.882475  0.882475
5003    GarageCars    GarageArea  0.882475  0.882475
4673   FireplaceQu    Fireplaces -0.837085  0.837085
4593    Fireplaces   FireplaceQu -0.837085  0.837085
3780     GrLivArea  TotRmsAbvGrd  0.825489  0.825489
4420  TotRmsAbvGrd     GrLivArea  0.825489  0.825489